[package]
name = "manulab-cli"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "manulab-cli-client"
path = "src/main.rs"

[dependencies]
tonic = "*"
prost = "*"
tonic-prost = "*"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-prost-build = "*"
